# Change these first
owner: snv-dev # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: NOVA Spektrum
    url: https://novaspektrum.no
  - name: Nor-Shipping
    url: https://nor-shipping.com
  - name: Lillestrøm Lobby
    url: https://lillestromlobby.no
  - name: Oslo Motor Show
    url: https://oslomotorshow.no
  - name: Camp Villmark
    url: https://campvillmark.no
  - name: Oslo Design Fair
    url: https://oslodesignfair.no
  - name: NOVA Talks
    url: https://novatalks.no
  - name: Hagemessen
    url: https://hagemessen.no
  - name: Agroteknikk
    url: https://agroteknikk.no
  - name: Transport & Logistikk
    url: https://transport-logistikk.no
  - name: Park og anleggsmessen
    url: https://poga.no
  - name: Automessen
    url: https://automessen.no
  - name: UMAMI Arena
    url: https://umamiarena.no
  - name: MC-messen
    url: https://mcmessen.no
  - name: Dyr for Alle
    url: https://dyrforalle.no
  - name: Oslo Dog Show
    url: https://oslodogshow.no
  - name: Spektrumkvarteret
    url: https://spektrumkvarteret.no
  - name: Lillestrøm NXT
    url: https://lillestromnxt.no
  - name: NOVA Studios
    url: https://novastudios.no
  - name: NOVA Spektrum Design
    url: https://novaspektrumdesign.no
  - name: NOVA Konsert
    url: https://novakonsert.no
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.nova.onl
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/snv-dev/upptime/master/assets/Nova_Spektrum-Logo-Horizontal-hvit.svg
  name: Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  footer:  

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
